"""initial migration

Revision ID: c4606995635b
Revises:
Create Date: 2025-03-22 13:59:01.331774

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4606995635b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemons",
        sa.Column(
            "incr_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("base_experience", sa.Integer(), nullable=False),
        sa.Column("abilities", sa.String(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("raw_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("incr_id"),
    )
    op.create_index(op.f("ix_pokemons_id"), "pokemons", ["id"], unique=True)
    op.create_index(op.f("ix_pokemons_incr_id"), "pokemons", ["incr_id"], unique=False)
    op.create_index(op.f("ix_pokemons_name"), "pokemons", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pokemons_name"), table_name="pokemons")
    op.drop_index(op.f("ix_pokemons_incr_id"), table_name="pokemons")
    op.drop_index(op.f("ix_pokemons_id"), table_name="pokemons")
    op.drop_table("pokemons")
    # ### end Alembic commands ###
